const menu = [
  {
    id: 1,
    title: 'strawberry banana pancakes',
    category: 'breakfast',
    price: 14.99,
    img: './images/item-1strawberryBananaPancakes.jpeg',
    desc: `4 pancakes filled with fresh banana slices. Topped with glazed strawberries & more banana slices`,
  },
  {
    id: 2,
    title: 'cheeseburger',
    category: 'lunch',
    price: 10.99,
    img: './images/item-2cheeseburger.jpeg',
    desc: `10oz beef patty, diced white onion, pickles, double American cheese, ketchup, mustard, bun `,
  },
  {
    id: 3,
    title: 'strawberry milkshake',
    category: 'shakes',
    price: 9.99,
    img: './images/item-3strawberryMilkshake.jpeg',
    desc: `Delightful mix of strawberries, milk, and vanilla ice cream, topped off with whipped cream `,
  },
  {
    id: 4,
    title: 'country omelette',
    category: 'breakfast',
    price: 14.99,
    img: './images/item-4countryOmelette.jpeg',
    desc: `Brimming with a blend of diced ham, onions, crisp celery and green peppers folded into a rich, luscious cheese sauce. With hashed browns tucked inside `,
  },
  {
    id: 5,
    title: 'steak',
    category: 'lunch',
    price: 19.99,
    img: './images/item-5steak.jpeg',
    desc: `Juicy, lean, and tender steak loaded with flavor `,
  },
  {
    id: 6,
    title: 'banana milkshake',
    category: 'shakes',
    price: 9.99,
    img: './images/item-6bananaMilkshake.jpeg',
    desc: `Perfect ratio of bananas, ice cream, and milk, topped off with whipped cream `,
  },
  {
    id: 7,
    title: 'chicken & waffles',
    category: 'breakfast',
    price: 14.99,
    img: './images/item-7chickenWaffles.jpeg',
    desc: `Buttermilk battered fried chicken, waffle & syrup `,
  },
  {
    id: 8,
    title: 'fried chicken',
    category: 'lunch',
    price: 14.99,
    img: './images/item-8friedChicken.jpeg',
    desc: `Well-seasoned, flavorful, and crispy fried chicken `,
  },
  {
    id: 9,
    title: 'chocolate milkshake',
    category: 'shakes',
    price: 9.99,
    img: './images/item-9chocolateMilkshake.jpeg',
    desc: `Blend of chocolate syrup, vanilla ice cream, fudge sauce, and topped off with whipped cream`,
  },
];

export default menu;